### ISSUE TITLE
Setter validation

### ISSUE THREAD

**Issue by Hout** [Ben-G/Validated#2]
Interesting lib! :+1: 
I noticed that it applies to value types that are checked on initialisation and that are immutable.
It would be nice to be able to have the validation in the setter too in case of a mutating type.

**Comment by Ben-G** [comment]
@Hout this sounds like a good idea. You're also bringing another good point to mind.

We should probably explicitly warn that `Validated` should only be used with value types or immutable reference types. The built in guarantees become meaningless when a reference type can be modified without the validator noticing.

**Comment by Ben-G** [comment]
Hey @Hout. Thanks a lot for the suggestion. For right now I consider the idea to be a little bit outside of the scope of this lib. Potential problems with reference types (untracked changes, threading issues, etc.) cannot be tackled the way they would need to be right now.

Therefore I'd rather like to keep the feature set limited but the guarantees this library can make strong.

🌟 Thanks a lot again 🌟
